name: BossBarMessage
main: me.itsnathang.bossbarmessage.BossBarMessage
author: NathanG
version: ${version}
softdepend: [PlaceholderAPI]
commands:
  bossbarmessage:
    aliases: [bm]
    description: Boss Bar Message Main Command
permissions:
  bossbarmessage.admin:
    default: op
    description: Allows user to use /bossbarmessage
