name: BossBarMessage
main: me.itsnathang.bossbarmessage.BossBarMessage
author: NathanG
version: ${version}
softdepend: [PlaceholderAPI]
commands:
  bossbarmessage:
    aliases: [bm]
    description: Initial Command